spring:
  application:
    name: authentication-service
  datasource:
    ## todo: credentials should be stored somewhere
    url: jdbc:postgresql://jrm-dev-db-1.cly0ayca2mpe.ap-southeast-2.rds.amazonaws.com:5432/postgres
    username: master
    password: 'master69'
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true