spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:postgresqljrm-db-1.cly0ayca2mpe.ap-southeast-2.rds.amazonaws.com:5432/jrm-db-1
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  server:
    port: 8080